/**
 * 对话辅助作业（`chat_assist_jobs` / worker）错误码，与 API 层 `ERROR_CODES` 命名空间分离。
 */
export const CHAT_ASSIST_JOB_ERROR_CODES = {
  CHAT_ASSIST_JOB_FAILED: 'CHAT_ASSIST_JOB_FAILED',
  CHAT_ASSIST_PROCESSING_FAILED: 'CHAT_ASSIST_PROCESSING_FAILED',
  CHAT_ASSIST_JOB_TIMED_OUT: 'CHAT_ASSIST_JOB_TIMED_OUT',
  CHAT_ASSIST_UPSTREAM_UNAVAILABLE: 'CHAT_ASSIST_UPSTREAM_UNAVAILABLE',
} as const;

export type ChatAssistJobErrorCode =
  (typeof CHAT_ASSIST_JOB_ERROR_CODES)[keyof typeof CHAT_ASSIST_JOB_ERROR_CODES];

/** Worker 侧处理超时（毫秒）。可被 env `CHAT_ASSIST_JOB_TIMEOUT_MS` 覆盖（与润色 `POLISH_JOB_TIMEOUT_MS` 对齐）。 */
export const CHAT_ASSIST_JOB_TIMEOUT_MS_DEFAULT = 30_000;
export const CHAT_ASSIST_JOB_UI_STALE_MS_DEFAULT = 35_000;
