export const ERROR_CODES = {
  HEALTH_CHECK_FAILED: 'HEALTH_CHECK_FAILED',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  /** 未登录或会话无效 */
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  /** 登录/注册泛化错误（防枚举） */
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  /** 账号已禁用 */
  AUTH_ACCOUNT_DISABLED: 'AUTH_ACCOUNT_DISABLED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  CSRF_INVALID: 'CSRF_INVALID',
  THROTTLE_LIMIT: 'THROTTLE_LIMIT',
  RESUME_NOT_FOUND: 'RESUME_NOT_FOUND',
  /** 库内简历 JSON 与当前 schema 不一致（迁移/脏数据） */
  RESUME_DOCUMENT_INVALID: 'RESUME_DOCUMENT_INVALID',
  /** 导出任务不存在 */
  EXPORT_JOB_NOT_FOUND: 'EXPORT_JOB_NOT_FOUND',
  SHARE_NOT_FOUND: 'SHARE_NOT_FOUND',
  SHARE_TOKEN_INVALID: 'SHARE_TOKEN_INVALID',
  SHARE_CREATE_FORBIDDEN: 'SHARE_CREATE_FORBIDDEN',
  /** 分享目标简历不存在 */
  SHARE_RESUME_NOT_FOUND: 'SHARE_RESUME_NOT_FOUND',
  /** 分享链接需要密码才能访问 */
  SHARE_PASSWORD_REQUIRED: 'SHARE_PASSWORD_REQUIRED',
  /** 分享密码不正确 */
  SHARE_PASSWORD_INVALID: 'SHARE_PASSWORD_INVALID',
  /** 密码校验请求过于频繁 */
  SHARE_PASSWORD_RATE_LIMITED: 'SHARE_PASSWORD_RATE_LIMITED',
  /** 分享链接已过期 */
  SHARE_EXPIRED: 'SHARE_EXPIRED',
  /** 当前简历未达到可分享标准（创建分享时） */
  SHARE_NOT_READY: 'SHARE_NOT_READY',
  /** 润色任务不存在 */
  POLISH_JOB_NOT_FOUND: 'POLISH_JOB_NOT_FOUND',
  /** 无权访问该润色任务 */
  POLISH_JOB_FORBIDDEN: 'POLISH_JOB_FORBIDDEN',
  /** 润色目标定位无效（找不到对应条目/要点） */
  POLISH_REQUEST_INVALID_TARGET: 'POLISH_REQUEST_INVALID_TARGET',
  /** 对话辅助任务不存在 */
  CHAT_ASSIST_JOB_NOT_FOUND: 'CHAT_ASSIST_JOB_NOT_FOUND',
  /** 无权访问该对话辅助任务 */
  CHAT_ASSIST_JOB_FORBIDDEN: 'CHAT_ASSIST_JOB_FORBIDDEN',
  /** 运营聚合接口：令牌缺失或错误 */
  OPS_METRICS_UNAUTHORIZED: 'OPS_METRICS_UNAUTHORIZED',
  /** 运营聚合：未配置 OPS_METRICS_TOKEN，接口不可用 */
  OPS_METRICS_NOT_CONFIGURED: 'OPS_METRICS_NOT_CONFIGURED',
  /** requestId 排障：未找到或已过期 */
  REQUEST_ID_NOT_FOUND: 'REQUEST_ID_NOT_FOUND',
  /** 会话不存在 */
  CHAT_SESSION_NOT_FOUND: 'CHAT_SESSION_NOT_FOUND',
  /** 无权访问该会话 */
  CHAT_SESSION_FORBIDDEN: 'CHAT_SESSION_FORBIDDEN',
  /** partial unique 约束冲突：同一简历已有活跃会话 */
  CHAT_SESSION_RESUME_CONFLICT: 'CHAT_SESSION_RESUME_CONFLICT',
  /** 导入任务不存在 */
  IMPORT_JOB_NOT_FOUND: 'IMPORT_JOB_NOT_FOUND',
  /** 导入请求过于频繁 */
  IMPORT_RATE_LIMITED: 'IMPORT_RATE_LIMITED',
  /** 该会话已导入或正在导入简历，不可重复上传 */
  IMPORT_SESSION_ALREADY_USED: 'IMPORT_SESSION_ALREADY_USED',
  /** 试用额度不足，需订阅 */
  CREDITS_EXHAUSTED: 'CREDITS_EXHAUSTED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
