/**
 * 异步导入作业（worker / DB `import_jobs`）错误码。
 */
export const IMPORT_JOB_ERROR_CODES = {
  IMPORT_JOB_FAILED: 'IMPORT_JOB_FAILED',
  IMPORT_UNSUPPORTED_FORMAT: 'IMPORT_UNSUPPORTED_FORMAT',
  IMPORT_PARSE_FAILED: 'IMPORT_PARSE_FAILED',
  IMPORT_LLM_FAILED: 'IMPORT_LLM_FAILED',
  IMPORT_STORAGE_FAILED: 'IMPORT_STORAGE_FAILED',
  IMPORT_EMPTY_CONTENT: 'IMPORT_EMPTY_CONTENT',
} as const;

export type ImportJobErrorCode =
  (typeof IMPORT_JOB_ERROR_CODES)[keyof typeof IMPORT_JOB_ERROR_CODES];
