export const POLISH_JOB_ERROR_CODES = {
  POLISH_JOB_FAILED: 'POLISH_JOB_FAILED',
  POLISH_TEXT_EXTRACTION_FAILED: 'POLISH_TEXT_EXTRACTION_FAILED',
  POLISH_PROCESSING_FAILED: 'POLISH_PROCESSING_FAILED',
  POLISH_JOB_TIMED_OUT: 'POLISH_JOB_TIMED_OUT',
  POLISH_UPSTREAM_UNAVAILABLE: 'POLISH_UPSTREAM_UNAVAILABLE',
} as const;

export type PolishJobErrorCode =
  (typeof POLISH_JOB_ERROR_CODES)[keyof typeof POLISH_JOB_ERROR_CODES];

/**
 * Worker 侧处理超时（毫秒）。可被 env `POLISH_JOB_TIMEOUT_MS` 覆盖。
 * 前端 UI "长时间无终态" 提示阈值可用 `POLISH_JOB_UI_STALE_MS`。
 */
export const POLISH_JOB_TIMEOUT_MS_DEFAULT = 30_000;
export const POLISH_JOB_UI_STALE_MS_DEFAULT = 35_000;
